baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'æˆ‘çš„åšå®¢'
theme = 'stack'

[params]
  mainSections = ["posts"]
  
  [params.sidebar]
    emoji = "ğŸ˜„"
    subtitle = "è®°å½•å­¦ä¹ ä¸ç”Ÿæ´»"
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/avatar.png"

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives" },
      { type = "categories" },
      { type = "tag-cloud" }
    ]
    page = [
      { type = "toc" }
    ]

[menu]
  [[menu.main]]
    name = "é¦–é¡µ"
    url = "/"
    weight = 1
    params = { icon = "home" }
  
  [[menu.main]]
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 2
    params = { icon = "archives" }
  
  [[menu.main]]
    name = "æœç´¢"
    url = "/search/"
    weight = 3
    params = { icon = "search" }
  
  [[menu.main]]
    name = "å‹é“¾"
    url = "/links/"
    weight = 4
    params = { icon = "link" }

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Austoin"
    params = { icon = "brand-github", newTab = true }
  
  [[menu.social]]
    identifier = "email"
    name = "Email"
    url = "mailto:mdd14090@gmail.com"
    params = { icon = "mail", newTab = false }
